---
# Production environment variables for fail2ban
# These override the defaults in group_vars/all.yml

# Stricter security settings for production
fail2ban_default_bantime: 7200      # 2 hours
fail2ban_default_findtime: 300      # 5 minutes
fail2ban_default_maxretry: 3        # Stricter retry limit

# Production email notifications
fail2ban_destemail: security@company.com
fail2ban_sender: fail2ban-prod@company.com
fail2ban_sendername: "Fail2Ban Production"

# Enhanced logging for production
fail2ban_loglevel: WARNING
fail2ban_logtarget: /var/log/fail2ban.log

# Production-specific jails with stricter settings
fail2ban_jails:
  - name: sshd
    enabled: true
    port: ssh
    filter: sshd
    logpath: /var/log/secure
    maxretry: 3
    bantime: 7200
    findtime: 300
    backend: systemd
  - name: httpd-auth
    enabled: true
    port: http,https
    filter: apache-auth
    logpath: /var/log/httpd/error_log
    maxretry: 5
    bantime: 3600
    findtime: 600
  - name: httpd-badbots
    enabled: true
    port: http,https
    filter: apache-badbots
    logpath: /var/log/httpd/access_log
    bantime: 86400
    maxretry: 1
    findtime: 3600
  - name: nginx-http-auth
    enabled: true
    port: http,https
    filter: nginx-http-auth
    logpath: /var/log/nginx/error.log
    maxretry: 5
    bantime: 3600
    findtime: 600
  - name: postfix
    enabled: true
    port: smtp,465,submission
    filter: postfix
    logpath: /var/log/maillog
    maxretry: 3
    bantime: 7200
    findtime: 600

# Production whitelist - add your management networks
fail2ban_ignoreip:
  - 127.0.0.1/8
  - ::1
  - 10.0.0.0/24        # Management network
  - 192.168.100.0/24   # Admin network
  # Add your specific production networks here

# Database purge more frequently in production
fail2ban_dbpurgeage: 43200  # 12 hours

# Use email notifications with whois info
fail2ban_default_action: "%(action_mwl)s"