---
# AWX Inventory for fail2ban deployment
# This inventory file provides examples for different server groups
# Customize according to your infrastructure

all:
  vars:
    # Global variables for all hosts
    ansible_user: ansible
    ansible_become: true
    ansible_become_method: sudo
    ansible_python_interpreter: /usr/bin/python3
    
    # fail2ban global configuration
    fail2ban_loglevel: INFO
    fail2ban_default_bantime: 3600
    fail2ban_default_findtime: 600
    fail2ban_default_maxretry: 5
    
  children:
    # Production servers
    production:
      vars:
        # Production-specific variables
        fail2ban_default_bantime: 7200  # 2 hours
        fail2ban_default_maxretry: 3    # Stricter for production
        fail2ban_destemail: security@company.com
        fail2ban_jails:
          - name: sshd
            enabled: true
            port: ssh
            filter: sshd
            logpath: /var/log/secure
            maxretry: 3
            bantime: 7200
            findtime: 600
          - name: httpd-auth
            enabled: true
            port: http,https
            filter: apache-auth
            logpath: /var/log/httpd/error_log
            maxretry: 5
            bantime: 3600
      hosts:
        # Example production hosts - replace with your actual servers
        prod-web-01:
          ansible_host: 10.0.1.10
        prod-web-02:
          ansible_host: 10.0.1.11
        prod-db-01:
          ansible_host: 10.0.1.20
          fail2ban_jails:
            - name: sshd
              enabled: true
              port: ssh
              filter: sshd
              logpath: /var/log/secure
              maxretry: 2  # Even stricter for database servers
              bantime: 14400  # 4 hours
              findtime: 300
    
    # Staging servers
    staging:
      vars:
        # Staging-specific variables
        fail2ban_default_bantime: 1800  # 30 minutes
        fail2ban_default_maxretry: 5
        fail2ban_destemail: devops@company.com
        fail2ban_jails:
          - name: sshd
            enabled: true
            port: ssh
            filter: sshd
            logpath: /var/log/secure
            maxretry: 5
            bantime: 1800
            findtime: 600
      hosts:
        # Example staging hosts - replace with your actual servers
        staging-web-01:
          ansible_host: 10.0.2.10
        staging-db-01:
          ansible_host: 10.0.2.20
    
    # Development servers
    development:
      vars:
        # Development-specific variables
        fail2ban_default_bantime: 600   # 10 minutes
        fail2ban_default_maxretry: 10   # More lenient for development
        fail2ban_destemail: dev@company.com
        fail2ban_jails:
          - name: sshd
            enabled: true
            port: ssh
            filter: sshd
            logpath: /var/log/secure
            maxretry: 10
            bantime: 600
            findtime: 600
      hosts:
        # Example development hosts - replace with your actual servers
        dev-server-01:
          ansible_host: 10.0.3.10
        dev-server-02:
          ansible_host: 10.0.3.11
    
    # Web servers group (cross-environment)
    webservers:
      vars:
        fail2ban_jails:
          - name: sshd
            enabled: true
            port: ssh
            filter: sshd
            logpath: /var/log/secure
            maxretry: 3
            bantime: 3600
            findtime: 600
          - name: httpd-auth
            enabled: true
            port: http,https
            filter: apache-auth
            logpath: /var/log/httpd/error_log
            maxretry: 6
            bantime: 1800
          - name: httpd-badbots
            enabled: true
            port: http,https
            filter: apache-badbots
            logpath: /var/log/httpd/access_log
            bantime: 86400
            maxretry: 1
      hosts:
        prod-web-01:
        prod-web-02:
        staging-web-01:
    
    # Database servers group (cross-environment)
    dbservers:
      vars:
        fail2ban_jails:
          - name: sshd
            enabled: true
            port: ssh
            filter: sshd
            logpath: /var/log/secure
            maxretry: 2
            bantime: 7200
            findtime: 300
      hosts:
        prod-db-01:
        staging-db-01:
    
    # CentOS/RHEL specific group
    centos_servers:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        fail2ban_default_backend: systemd
      hosts:
        prod-web-01:
        prod-web-02:
        prod-db-01:
        staging-web-01:
        staging-db-01:
        dev-server-01:
        dev-server-02: